# Generated by Django 4.1.10 on 2023-09-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_bim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало тестирования')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец тестирования')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Тест пройден')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quiz_bim.testbim', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогрес',
                'verbose_name_plural': 'Прогресы',
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='ProgressTestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='quiz_bim.answerbim', verbose_name='Ответ')),
                ('progress_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='progress.progresstest', verbose_name='Прогрес теста')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz_bim.questionbim', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Впопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
                'db_table': 'progress_answers',
            },
        ),
    ]
