# Generated by Django 4.1.10 on 2023-09-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_bim', '0002_rename_title_testbim_test_title'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresstestanswers',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы'},
        ),
        migrations.RemoveField(
            model_name='progresstestanswers',
            name='user',
        ),
        migrations.AlterField(
            model_name='progresstestanswers',
            name='progress_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='progress.progresstest', verbose_name='Прогресс теста'),
        ),
        migrations.AlterField(
            model_name='progresstestanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='test_bim.questionbim', verbose_name='Вопрос'),
        ),
    ]
