# Generated by Django 4.1.10 on 2023-11-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstest',
            name='in_progress',
            field=models.BooleanField(default=True, verbose_name='Тест в процессе'),
        ),
    ]
