# Generated by Django 4.1.13 on 2023-11-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bim', '0004_alter_answerbim_options_alter_questionbim_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_progresstest_in_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresstest',
            options={'verbose_name': 'Test progress', 'verbose_name_plural': 'Test progress'},
        ),
        migrations.AlterModelOptions(
            name='progresstestanswers',
            options={'verbose_name': 'Question-Answer', 'verbose_name_plural': 'Questions-Answers'},
        ),
        migrations.AlterField(
            model_name='progresstest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test end time'),
        ),
        migrations.AlterField(
            model_name='progresstest',
            name='in_progress',
            field=models.BooleanField(default=True, verbose_name='Test in progress'),
        ),
        migrations.AlterField(
            model_name='progresstest',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Test passed'),
        ),
        migrations.AlterField(
            model_name='progresstest',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Test start time'),
        ),
        migrations.AlterField(
            model_name='progresstest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quiz_bim.quizbim', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='progresstest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='progresstestanswers',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='quiz_bim.answerbim', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='progresstestanswers',
            name='progress_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='progress.progresstest', verbose_name='Test progress'),
        ),
        migrations.AlterField(
            model_name='progresstestanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='quiz_bim.questionbim', verbose_name='Question'),
        ),
    ]
