services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
      for fixture in 01_auth.json 02_accounts.json 03_currencies.json 04_modules.json 05_quiz_bim.json 06_step.json 07_tasks.json 08_sites.json 09_socialaccount.json 10_subscription.json; do
        python manage.py loaddata fixtures/$$fixture
      done &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    hostname: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A accessibleBIM worker --beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - db
    env_file:
      - .env.dev
    restart: always
    volumes:
      - .:/usr/src/app/

volumes:
  postgres_data:
