services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py migrate &&
      for fixture in 01_auth.json 02_accounts.json 03_currencies.json 04_modules.json 05_quiz_bim.json 06_step.json 07_tasks.json 08_sites.json 09_socialaccount.json 10_subscription.json; do
        python manage.py loaddata fixtures/$$fixture
      done &&
      python manage.py collectstatic --noinput &&
      gunicorn accessibleBIM.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    restart: always
    depends_on:
      - db
  db:
    image: postgres:15
    env_file:
      - ./.env.prod
    restart: always
    environment:
      TZ: 'Asia/Bishkek'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    environment:
      TZ: 'Asia/Bishkek'
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: "redis:alpine"
    hostname: redis
    restart: always
    environment:
      TZ: 'Asia/Bishkek'
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A accessibleBIM worker --beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    restart: always
    environment:
      TZ: 'Asia/Bishkek'
    volumes:
      - .:/usr/src/app/

volumes:
  postgres_data:
  static_volume:
  media_volume:
