# Generated by Django 4.1.10 on 2023-09-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Название модуля')),
                ('description', models.TextField(max_length=150, verbose_name='Описание модуля')),
                ('image', models.ImageField(upload_to='course', verbose_name='Фото для курса')),
                ('learnTime', models.IntegerField(default=0, verbose_name='Время на прохождение курса')),
                ('courseTarget_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='modules.coursemodel')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseTargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Для кого предназначен курс')),
                ('description', models.TextField(max_length=150, verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'Целевая аудитория',
                'verbose_name_plural': 'Целевая аудитория',
                'db_table': 'CourseTarget',
            },
        ),
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Название модуля')),
                ('description', models.TextField(max_length=150, verbose_name='Описание модуля')),
                ('image', models.ImageField(upload_to='module', verbose_name='Фото для модуля')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('corp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место работы')),
                ('experience', models.CharField(blank=True, max_length=150, null=True, verbose_name='Опыт работы')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учитель',
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ct_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='modules.coursemodel', verbose_name='Курсы')),
                ('ct_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='modules.teachermodel', verbose_name='Учителя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='modules.modulemodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', through='modules.CourseTeacherModel', to='modules.teachermodel'),
        ),
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Название модуля')),
                ('description', models.TextField(max_length=150, verbose_name='Описание модуля')),
                ('serial_number', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_course', to='modules.coursemodel', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Главы',
                'verbose_name_plural': 'Глава',
                'db_table': 'Chapter',
            },
        ),
    ]
