# Generated by Django 4.1.10 on 2023-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetargetmodel',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Подробное описание'),
        ),
    ]
