# Generated by Django 4.1.10 on 2023-09-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_coursetargetmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='courseTarget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='modules.coursetargetmodel'),
        ),
        migrations.AlterModelTable(
            name='chaptermodel',
            table='chapter',
        ),
        migrations.AlterModelTable(
            name='coursemodel',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursetargetmodel',
            table='course_target',
        ),
        migrations.AlterModelTable(
            name='modulemodel',
            table='module',
        ),
        migrations.AlterModelTable(
            name='teachermodel',
            table='teacher',
        ),
    ]
