# Generated by Django 4.1.10 on 2023-09-12 16:06

from django.db import migrations, models
import modules.models.module


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_coursemodel_coursetarget_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание главы'),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название главы'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='modulemodel',
            name='image',
            field=models.ImageField(upload_to=modules.models.module.module_upload_to, verbose_name='Фото для модуля'),
        ),
    ]
