# Generated by Django 4.1.10 on 2023-09-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_coursemodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Описание главы'),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название главы'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='language',
            field=models.CharField(choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KG', 'Кыргызский')], max_length=10, verbose_name='Язык занятия'),
        ),
    ]
