# Generated by Django 4.1.10 on 2023-09-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_chaptermodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chaptermodel',
            table='chapters',
        ),
        migrations.AlterModelTable(
            name='coursemodel',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='coursetargetmodel',
            table='course_targets',
        ),
        migrations.AlterModelTable(
            name='modulemodel',
            table='modules',
        ),
        migrations.AlterModelTable(
            name='teachermodel',
            table='teachers',
        ),
    ]
