# Generated by Django 4.1.10 on 2023-09-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_coursemodel_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptermodel',
            options={'verbose_name': 'Главы', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
