# Generated by Django 4.1.10 on 2023-09-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_chaptermodel_table_alter_coursemodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chaptermodel',
            table='chapter',
        ),
        migrations.AlterModelTable(
            name='coursemodel',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursetargetmodel',
            table='course_target',
        ),
        migrations.AlterModelTable(
            name='modulemodel',
            table='module',
        ),
        migrations.AlterModelTable(
            name='teachermodel',
            table='teacher',
        ),
    ]
