# Generated by Django 4.1.10 on 2023-09-12 16:52

from django.db import migrations, models
import modules.models.courses


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_chaptermodel_table_alter_coursemodel_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(upload_to=modules.models.courses.courses_upload_to, verbose_name='Фото для курса'),
        ),
    ]
