# Generated by Django 4.1.10 on 2023-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_chaptermodel_options_alter_coursemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='learnTime',
            field=models.IntegerField(default=0, verbose_name='Время на прохождение курса (часы)'),
        ),
    ]
