# Generated by Django 4.1.10 on 2023-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_coursemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='language',
            field=models.CharField(choices=[('KG', 'Кыргызский'), ('RU', 'Русский'), ('EN', 'Английский')], default='RU', max_length=10, verbose_name='Тип занятия'),
            preserve_default=False,
        ),
    ]
