# Generated by Django 4.1.10 on 2023-10-13 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_textmodel_text_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0007_alter_coursemodel_learntime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('0', 'In progress'), ('1', 'Finished')], default=0, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало шага')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец шага')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.stepmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по курсу',
                'verbose_name_plural': 'Прогрессы по курсу',
                'db_table': 'user_course_progress',
            },
        ),
    ]
