# Generated by Django 4.1.10 on 2023-11-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_filemodel_file_title_and_more'),
        ('modules', '0008_usercourseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='courseTarget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='modules.coursetargetmodel', verbose_name='Целевая аудитория курса'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', through='modules.CourseTeacherModel', to='modules.teachermodel', verbose_name='Преподаватели курса'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_course_progress', to='step.stepmodel'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Конец шага'),
        ),
    ]
