# Generated by Django 4.1.10 on 2023-11-08 16:11

from django.db import migrations, models
import modules.models.courses


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_chaptermodel_options_alter_chaptermodel_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Course description'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(upload_to=modules.models.courses.courses_upload_to, verbose_name='Course image'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='language',
            field=models.CharField(choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KG', 'Кыргызский')], max_length=10, verbose_name='Course language'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='learnTime',
            field=models.IntegerField(default=0, verbose_name='Course learn time'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Course title'),
        ),
    ]
