# Generated by Django 4.1.10 on 2023-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_coursemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetargetmodel',
            options={'verbose_name': 'Course target', 'verbose_name_plural': 'Course targets'},
        ),
        migrations.AlterField(
            model_name='coursetargetmodel',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Target description'),
        ),
        migrations.AlterField(
            model_name='coursetargetmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Target title'),
        ),
    ]
