# Generated by Django 4.1.10 on 2023-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_alter_coursetargetmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='corp',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About teacher'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='experience',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='father_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Father name'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Last name'),
        ),
    ]
