# Generated by Django 4.1.10 on 2023-11-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_alter_teachermodel_options_alter_teachermodel_corp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourseprogress',
            options={'verbose_name': 'Course progress', 'verbose_name_plural': 'Course progress'},
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Step start'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='status',
            field=models.IntegerField(choices=[('0', 'In progress'), ('1', 'Finished')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Step finish'),
        ),
    ]
