# Generated by Django 4.1.10 on 2023-11-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_alter_usercourseprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
