# Generated by Django 4.1.13 on 2023-11-13 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_filemodel_file_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0015_alter_coursemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_course', to='modules.coursemodel', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='courseTarget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='modules.coursetargetmodel', verbose_name='Target audience'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='modules.modulemodel', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', through='modules.CourseTeacherModel', to='modules.teachermodel', verbose_name='Teachers'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_course_progress', to='step.stepmodel', verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
