# Generated by Django 4.1.13 on 2023-11-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_coursemodel_coursetarget_id_and_more'),
        ('modules', '0016_alter_chaptermodel_course_and_more'),
    ]

    operations = [
    ]
