# Generated by Django 4.1.10 on 2023-09-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_alter_coursemodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='language',
            field=models.CharField(choices=[('RU', 'Русский'), ('EN', 'Английский'), ('KG', 'Кыргызский')], max_length=10, verbose_name='Язык занятия'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе'),
        ),
    ]
