# Generated by Django 4.1.13 on 2023-11-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_merge_20231115_2231'),
        ('modules', '0018_alter_coursemodel_coursetarget_id_and_more'),
    ]

    operations = [
    ]
