# Generated by Django 4.1.10 on 2023-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0021_alter_coursemodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Описание главы'),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название главы'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='language',
            field=models.CharField(choices=[('EN', 'Английский'), ('RU', 'Русский'), ('KG', 'Кыргызский')], max_length=10, verbose_name='Язык занятия'),
        ),
    ]
