# Generated by Django 4.1.10 on 2023-09-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('goal_currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cоздано')),
                ('source', models.CharField(max_length=500, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'currency_rate',
            },
        ),
    ]
