# Generated by Django 4.1.10 on 2023-09-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyratemodel',
            name='base_currency',
            field=models.PositiveIntegerField(choices=[('USD', 'USD'), ('RUB', 'RUB')], verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='currencyratemodel',
            name='goal_currency',
            field=models.PositiveIntegerField(choices=[('USD', 'USD'), ('RUB', 'RUB')], verbose_name='Валюта'),
        ),
    ]
