# Generated by Django 4.1.10 on 2023-09-28 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currencyratemodel_base_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyratemodel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
