# Generated by Django 4.1.10 on 2023-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bim', '0002_rename_title_testbim_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbim',
            name='questions_qty',
            field=models.PositiveIntegerField(verbose_name='Количество вопросов'),
        ),
    ]
