# Generated by Django 4.1.10 on 2023-09-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.IntegerField(verbose_name='Цена за курс')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка на курс')),
                ('end_date', models.DateTimeField(verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='modules.coursemodel', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписка',
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='UsersSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_subscriptions', to='subscription.subscriptionmodel', verbose_name='Подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
