# Generated by Django 4.1.10 on 2023-09-20 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.IntegerField(verbose_name='Цена за курс')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка на курс')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='modules.coursemodel', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписка',
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='UsersSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 19, 25, 44, 579939), verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность подписки')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_subscriptions', to='subscription.subscriptionmodel', verbose_name='Подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='user_subscription',
            field=models.ManyToManyField(through='subscription.UsersSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
