# Generated by Django 4.1.10 on 2023-09-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_alter_coursemodel_language'),
        ('subscription', '0003_subscriptionmodel_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='modules.coursemodel', verbose_name='Курс'),
        ),
    ]
