# Generated by Django 4.1.10 on 2023-09-24 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_userssubscription_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssubscription',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 10, 6, 5, 827643), verbose_name='Дата окончания подписки'),
        ),
    ]
