# Generated by Django 4.1.10 on 2023-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionmodel_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userssubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность подписки'),
        ),
    ]
