# Generated by Django 4.1.10 on 2023-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_userssubscription_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssubscription',
            name='end_time',
            field=models.DateTimeField(verbose_name='Дата окончания подписки'),
        ),
    ]
