# Generated by Django 4.1.10 on 2023-09-18 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscriptionmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssubscription',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 21, 30, 6, 997518), verbose_name='Дата окончания подписки'),
        ),
    ]
