# Generated by Django 4.1.10 on 2023-09-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_userssubscription_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionmodel',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='discount',
        ),
    ]
