# Generated by Django 4.1.10 on 2023-09-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_chaptermodel_options_alter_coursemodel_options'),
        ('subscription', '0005_alter_userssubscription_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionmodel',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='modules.coursemodel', verbose_name='Курс'),
        ),
    ]
