# Generated by Django 4.1.10 on 2023-09-20 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_userssubscription_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssubscription',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 6, 42, 29, 529942), verbose_name='Дата окончания подписки'),
        ),
    ]
