# Generated by Django 4.1.10 on 2023-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscriptionmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
