# Generated by Django 4.1.10 on 2023-09-20 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_userssubscription_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssubscription',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 7, 43, 12, 108201), verbose_name='Дата окончания подписки'),
        ),
    ]
