# Generated by Django 4.1.10 on 2023-10-16 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0009_remove_subscriptionmodel_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmodel',
            name='user_subscription',
            field=models.ManyToManyField(through='subscription.UsersSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
