from reports.views.sales_statistics_views.api.get_new_subscriptions_qty_view import get_new_subscriptions_qty_view
from reports.views.sales_statistics_views.api.get_popular_courses_view import get_popular_courses_view
