# Generated by Django 4.1.10 on 2023-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='company_name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.ManyToManyField(related_name='users', through='subscription.UsersSubscription', to='subscription.subscriptionmodel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_corp',
            field=models.IntegerField(choices=[(1, 'entrepreneur'), (2, 'limited_liability_company'), (3, 'opened joint stock company'), (4, 'closed joint stock company'), (5, 'additional liability company'), (6, 'state company'), (7, 'other typecorp')], default=7, verbose_name='company_type'),
        ),
    ]
