# Generated by Django 4.1.10 on 2023-09-21 16:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(default='Kyrgyzstan', max_length=2),
            preserve_default=False,
        ),
    ]
