# Generated by Django 4.1.10 on 2023-09-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
        ('accounts', '0003_customuser_country'),
    ]

    operations = [
    ]
