# Generated by Django 4.1.10 on 2023-09-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscription',
            new_name='subscriptions',
        ),
    ]
