# Generated by Django 4.1.10 on 2023-09-14 16:59

import accounts.models.custom_user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_email_verified_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.custom_user.CustomUserManager()),
            ],
        ),
    ]
