# Generated by Django 4.1.10 on 2023-10-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_view_admin_panel ', 'Can view admin panel'), ('can_grant_moderator_role', 'Can grant moderator role to other users'))},
        ),
    ]
