# Generated by Django 4.1.10 on 2023-09-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_subscription_customuser_subscriptions'),
        ('accounts', '0006_alter_customuser_managers'),
    ]

    operations = [
    ]
