# Generated by Django 4.1.10 on 2023-09-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20230915_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
    ]
