from reports.views.users_statistics_views.users_main_statistics_view import UsersMainStatisticsView
from reports.views.users_statistics_views.users_list_statistics_view import UsersListStatisticsView
