from reports.views.courses_statistics_views.api.get_steps_completed_qty_view import get_steps_completed_qty_view
from reports.views.courses_statistics_views.api.get_lesson_types_view import get_lesson_types_view
