# Generated by Django 4.1.10 on 2023-09-07 17:15

from django.db import migrations, models
import django.db.models.deletion
import step.models.file
import step.models.video


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_bim', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson_file', models.FileField(upload_to=step.models.file.file_upload_to, verbose_name='Файл занятия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('content', models.TextField(max_length=100000, verbose_name='Содержимое')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование видео')),
                ('description', models.CharField(max_length=500, verbose_name='Описание видео')),
                ('video_file', models.FileField(upload_to=step.models.video.video_upload_to, verbose_name='Файл видео')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('lesson_type', models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('test', 'Тест')], max_length=10, verbose_name='Тип занятия')),
                ('learn_time', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='modules.chaptermodel', verbose_name='Chapter')),
                ('file', models.ManyToManyField(related_name='step', to='step.filemodel', verbose_name='Файл')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='quiz_bim.testbim', verbose_name='Тест')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='step.textmodel', verbose_name='Текст')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='step.videomodel', verbose_name='Видео')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
