# Generated by Django 4.1.10 on 2023-09-20 19:25

from django.db import migrations, models
import django.db.models.deletion
import step.models.file
import step.models.video


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('quiz_bim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file_title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('lesson_file', models.FileField(upload_to=step.models.file.file_upload_to, verbose_name='Файл занятия')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text_title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('text_description', models.CharField(max_length=500, verbose_name='Описание')),
                ('content', models.TextField(max_length=100000, verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('video_title', models.CharField(max_length=250, verbose_name='Наименование видео')),
                ('video_description', models.CharField(max_length=500, verbose_name='Описание видео')),
                ('video_file', models.FileField(upload_to=step.models.video.video_upload_to, verbose_name='Файл видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('lesson_type', models.CharField(choices=[('test', 'Тест'), ('video', 'Видео'), ('text', 'Текст')], max_length=10, verbose_name='Тип занятия')),
                ('learn_time', models.PositiveIntegerField()),
                ('serial_number', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='modules.chaptermodel', verbose_name='Глава')),
                ('file', models.ManyToManyField(related_name='step', to='step.filemodel', verbose_name='Файлы')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='quiz_bim.quizbim', verbose_name='Тест')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='step.textmodel', verbose_name='Текст')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='step.videomodel', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'db_table': 'steps',
            },
        ),
    ]
