# Generated by Django 4.1.10 on 2023-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_alter_stepmodel_lesson_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='stepmodel',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='textmodel',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RenameField(
            model_name='textmodel',
            old_name='description',
            new_name='text_description',
        ),
        migrations.RenameField(
            model_name='textmodel',
            old_name='title',
            new_name='text_title',
        ),
        migrations.RenameField(
            model_name='videomodel',
            old_name='description',
            new_name='video_description',
        ),
        migrations.RenameField(
            model_name='videomodel',
            old_name='title',
            new_name='video_title',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_title',
            field=models.CharField(default='', max_length=250, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('test', 'Тест')], max_length=10, verbose_name='Тип занятия'),
        ),
        migrations.AlterModelTable(
            name='filemodel',
            table='files',
        ),
        migrations.AlterModelTable(
            name='stepmodel',
            table='steps',
        ),
        migrations.AlterModelTable(
            name='textmodel',
            table='texts',
        ),
        migrations.AlterModelTable(
            name='videomodel',
            table='videos',
        ),
    ]
