# Generated by Django 4.1.10 on 2023-09-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_alter_stepmodel_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='text_description',
            field=models.CharField(max_length=1500, verbose_name='Описание'),
        ),
    ]
