# Generated by Django 4.1.10 on 2023-09-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_alter_stepmodel_lesson_type'),
        ('step', '0002_alter_stepmodel_lesson_type_and_more'),
    ]

    operations = [
    ]
