# Generated by Django 4.1.10 on 2023-10-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ffmpeg', '0007_alter_convertingcommand_id_alter_video_id'),
        ('step', '0003_alter_textmodel_text_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='converted_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ffmpeg.video'),
        ),
    ]
