# Generated by Django 4.1.10 on 2023-10-16 17:35

from django.db import migrations, models
import step.models.file
import step.models.video


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_textmodel_text_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to=step.models.file.file_upload_to, verbose_name='Файл занятия'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, related_name='step', to='step.filemodel', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='learn_time',
            field=models.PositiveIntegerField(verbose_name='Примерное время на прохождение урока'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='content',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text_description',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Оглавление'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание видео'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=step.models.video.video_upload_to, verbose_name='Файл видео'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование видео'),
        ),
    ]
