#39_CRUD_progress_userAnswers_models
# Generated by Django 4.1.10 on 2023-09-12 13:55

# Generated by Django 4.1.10 on 2023-09-12 16:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_filemodel_options_alter_stepmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepmodel',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('test', 'Тест')], max_length=10, verbose_name='Тип занятия'),


        ),
    ]
