# Generated by Django 4.1.13 on 2023-11-13 17:37

from django.db import migrations, models
import django.db.models.deletion
import step.models.file
import step.models.video


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_alter_chaptermodel_course_and_more'),
        ('quiz_bim', '0003_alter_quizbim_questions_qty'),
        ('step', '0004_alter_filemodel_file_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='stepmodel',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='textmodel',
            options={'verbose_name': 'Text', 'verbose_name_plural': 'Texts'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='File title'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to=step.models.file.file_upload_to, verbose_name='Lesson file'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='modules.chaptermodel', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, related_name='step', to='step.filemodel', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='learn_time',
            field=models.PositiveIntegerField(verbose_name='Lesson learn time'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('test', 'Test')], max_length=10, verbose_name='Lesson type'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='serial_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='quiz_bim.quizbim', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='step.textmodel', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='step.videomodel', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='content',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Text content'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text_description',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Text description'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Text title'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Video description'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=step.models.video.video_upload_to, verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Video title'),
        ),
    ]
