# Generated by Django 4.1.10 on 2023-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_alter_stepmodel_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepmodel',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('test', 'Тест')], max_length=10, verbose_name='Тип занятия'),
        ),
    ]
