# Generated by Django 4.1.10 on 2023-09-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_alter_stepmodel_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepmodel',
            name='file',
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='lesson_type',
            field=models.CharField(choices=[('test', 'Тест'), ('text', 'Текст'), ('video', 'Видео')], max_length=10, verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='stepmodel',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='step', to='step.filemodel', verbose_name='Файл'),
        ),
    ]
