# Generated by Django 4.1.10 on 2023-09-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0009_alter_stepmodel_lesson_type'),
        ('step', '0009_remove_stepmodel_file_alter_stepmodel_lesson_type_and_more'),
    ]

    operations = [
    ]
