# Generated by Django 4.1.10 on 2023-09-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0010_merge_20230915_1947'),
        ('step', '0011_alter_stepmodel_lesson_type'),
    ]

    operations = [
    ]
