# Generated by Django 4.1.10 on 2023-09-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0012_merge_20230916_1141'),
        ('step', '0012_merge_20230916_1326'),
    ]

    operations = [
    ]
