# Generated by Django 4.1.10 on 2023-09-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_coursemodel_language'),
        ('step', '0013_merge_20230918_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmodel',
            name='serial_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='modules.chaptermodel', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='file',
            field=models.ManyToManyField(related_name='step', to='step.filemodel', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='lesson_type',
            field=models.CharField(choices=[('test', 'Тест'), ('text', 'Текст'), ('video', 'Видео')], max_length=10, verbose_name='Тип занятия'),
        ),
    ]
