# Generated by Django 4.1.10 on 2023-09-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0014_stepmodel_serial_number_alter_stepmodel_chapter_and_more'),
        ('step', '0022_alter_stepmodel_lesson_type'),
    ]

    operations = [
    ]
