# Generated by Django 4.1.10 on 2023-10-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbim',
            name='test_bim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bim', to='quiz_bim.quizbim', verbose_name='Тест Bim'),
        ),
        migrations.AlterField(
            model_name='quizbim',
            name='questions_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество выдаваемых вопросов за один тест'),
        ),
        migrations.AlterField(
            model_name='quizbim',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема тестирования'),
        ),
    ]
