# Generated by Django 4.1.10 on 2023-09-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizbim',
            name='questions_qty',
        ),
    ]
