# Generated by Django 4.1.10 on 2023-09-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testbim',
            old_name='title',
            new_name='test_title',
        ),
    ]
