# Generated by Django 4.1.13 on 2023-11-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bim', '0003_alter_quizbim_questions_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerbim',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='questionbim',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizbim',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterField(
            model_name='answerbim',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='answerbim',
            name='is_correct',
            field=models.BooleanField(choices=[(False, 'Wrong answer'), (True, 'Right answer')], default=False, verbose_name='Answer validation'),
        ),
        migrations.AlterField(
            model_name='answerbim',
            name='question_bim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_bim', to='quiz_bim.questionbim', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionbim',
            name='test_bim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bim', to='quiz_bim.quizbim', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='questionbim',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quizbim',
            name='questions_qty',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Questions quantity'),
        ),
        migrations.AlterField(
            model_name='quizbim',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Test title'),
        ),
    ]
