# Generated by Django 4.1.10 on 2023-09-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bim', '0003_alter_testbim_questions_qty'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE django_content_type SET app_label='quiz_bim' WHERE app_label='test_bim'; UPDATE django_migrations SET app='quiz_bim' WHERE app='test_bim'",
            "UPDATE django_content_type SET app_label='test_bim' WHERE app_label='quiz_bim'; UPDATE django_migrations SET app='test_bim' WHERE app='quiz_bim'"
        )
    ]
