from reports.views.users_statistics_views import UsersMainStatisticsView, UsersListStatisticsView, \
    UserDetailedStatisticsView
from reports.views.courses_statistics_views import CoursesMainStatisticsView, CoursesListStatisticsView
from reports.views.sales_statistics_views import SalesMainStatisticsView
