name: Prod Docker Build/Up

on:
  workflow_run:
    workflows: ["Run Test Django Prod"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build docker-compose.prod.yml --file Dockerfile.prod --tag my-image-name:$(date +%s)