name: Docker Image CI Dev

on:
  push:
    branches: #319_CI-CD
  pull_request:
    branches: #319_CI-CD


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}


          SCRIPT_AFTER: |
            cd AccessibleBIM/
            docker system prune -af
            docker compose -f docker-compose.prod.yml up -d --build