name: Docker Image CI Dev

on:
  push:
    branches: #319_CI-CD
  pull_request:
    branches: #319_CI-CD


jobs:
  deploy:
    runs-on: ubuntu- latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: S{{secrets.SSH HOST}} # IP address of the server you wish to ssh into
          key: S{{secrets.SSH KEY}} # Private or public key of the server
          username: S{{ secrets.SSH_ USERNAME }} # User of the server you want to ssh into

          script: |
            rm -R AccessibleBIM
            git clone --single-branch --branch #319_CI-CD git@github.com:Attractor-School-Python-16/AccessibleBIM.git
            echo ‘Deployment successful to digital ocean’
            cd AccessibleBIM
            docker compose -f docker-compose.prod.yml up -d --build